#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from fe.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "fe.y"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
extern FILE* yyin;
extern char* yytext;

extern void createWindow();
extern void applyProperty();
extern int assign();
extern int checkFree();
extern int getById();
extern void printEnv();

struct environment{
     char *identifiers[256];
     int ints[256];
     int nrints;
};
struct environment* envs[256];
struct environment* last_env;
struct environment* consts;
int envnr;

void enterEnv()
{
     struct environment* env = (void *)malloc(sizeof(struct environment));
     envs[envnr++] = env;
     last_env = env;
}

void exitEnv()
{
     free(envs[envnr]);
     envnr--;
     if (envnr>0)
          last_env = envs[envnr-1];
}


struct tuple{int x, y;};
struct window{
     struct tuple *size;
     char* caption;
};
struct component{
     char* name;
     void* value;
};

struct component* components[256];
struct component* last_comp;
int compnr;

void enterComp(char* name)
{
     struct component* c = (void *)malloc(sizeof(struct component));
     components[compnr++] = c;
     c->name = name;
     if (strcmp(name, "win")==0)
          c->value = (void *)malloc(sizeof(struct window));
     last_comp = c;
}

void exitComp()
{
     free(components[compnr]);
     compnr--;
     if (compnr>0)
          last_comp = components[compnr-1];
}


#line 75 "fe.y"
typedef union {
     int intval;
     struct tuple *tupleval;
     char* strval;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	TIP	258
#define	BGIN	259
#define	END	260
#define	ASSIGN	261
#define	PROCENT	262
#define	POINT	263
#define	MAIN	264
#define	RETURN	265
#define	LOOP	266
#define	POOL	267
#define	IF	268
#define	FI	269
#define	FOR	270
#define	ROF	271
#define	IN	272
#define	ELSE	273
#define	PRINT	274
#define	NR	275
#define	PROPERTY	276
#define	STRING	277
#define	ID	278


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int TIP;
static const int BGIN;
static const int END;
static const int ASSIGN;
static const int PROCENT;
static const int POINT;
static const int MAIN;
static const int RETURN;
static const int LOOP;
static const int POOL;
static const int IF;
static const int FI;
static const int FOR;
static const int ROF;
static const int IN;
static const int ELSE;
static const int PRINT;
static const int NR;
static const int PROPERTY;
static const int STRING;
static const int ID;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,TIP=258
	,BGIN=259
	,END=260
	,ASSIGN=261
	,PROCENT=262
	,POINT=263
	,MAIN=264
	,RETURN=265
	,LOOP=266
	,POOL=267
	,IF=268
	,FI=269
	,FOR=270
	,ROF=271
	,IN=272
	,ELSE=273
	,PRINT=274
	,NR=275
	,PROPERTY=276
	,STRING=277
	,ID=278


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::TIP=258;
const int YY_parse_CLASS::BGIN=259;
const int YY_parse_CLASS::END=260;
const int YY_parse_CLASS::ASSIGN=261;
const int YY_parse_CLASS::PROCENT=262;
const int YY_parse_CLASS::POINT=263;
const int YY_parse_CLASS::MAIN=264;
const int YY_parse_CLASS::RETURN=265;
const int YY_parse_CLASS::LOOP=266;
const int YY_parse_CLASS::POOL=267;
const int YY_parse_CLASS::IF=268;
const int YY_parse_CLASS::FI=269;
const int YY_parse_CLASS::FOR=270;
const int YY_parse_CLASS::ROF=271;
const int YY_parse_CLASS::IN=272;
const int YY_parse_CLASS::ELSE=273;
const int YY_parse_CLASS::PRINT=274;
const int YY_parse_CLASS::NR=275;
const int YY_parse_CLASS::PROPERTY=276;
const int YY_parse_CLASS::STRING=277;
const int YY_parse_CLASS::ID=278;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		181
#define	YYFLAG		-32768
#define	YYNTBASE	40

#define YYTRANSLATE(x) ((unsigned)(x) <= 278 ? yytranslate[x] : 59)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,    31,     2,     2,     2,     2,    32,
    33,    26,    24,    37,    25,    28,    27,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    30,     2,
    29,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    38,     2,    39,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    34,     2,    35,    36,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     5,     7,    10,    16,    22,    28,    30,    38,
    39,    48,    49,    59,    61,    64,    71,    80,    87,    98,
   103,   108,   112,   116,   120,   126,   128,   132,   133,   141,
   143,   147,   150,   152,   155,   164,   172,   177,   182,   187,
   192,   197,   202,   206,   208,   212,   216,   220,   224,   228,
   230,   235,   237,   241,   245,   249,   253,   257,   259,   264,
   266,   268,   273,   277,   279,   285,   287
};

static const short yyrhs[] = {    41,
    49,     0,    49,     0,    42,     0,    42,    41,     0,    28,
    23,    29,    55,    30,     0,    28,    23,    29,    56,    30,
     0,    28,    23,    29,    22,    30,     0,    43,     0,    31,
    23,    32,    55,    30,    33,    51,     0,     0,    28,    23,
    32,    33,    44,    34,    46,    35,     0,     0,    28,    23,
    32,    48,    33,    45,    34,    46,    35,     0,    47,     0,
    47,    46,     0,    13,    32,    56,    33,    46,    14,     0,
    13,    32,    56,    33,    46,    18,    46,    14,     0,    11,
    32,    56,    33,    46,    12,     0,    15,    32,    23,    17,
    56,    36,    56,    33,    46,    16,     0,    23,    29,    56,
    30,     0,    23,    29,    55,    30,     0,    10,    56,    30,
     0,    10,    55,    30,     0,    10,    22,    30,     0,    19,
    32,    56,    33,    30,     0,    23,     0,    23,    37,    48,
     0,     0,    50,     9,    32,    55,    30,    33,    51,     0,
    30,     0,    34,    52,    35,     0,    34,    35,     0,    53,
     0,    53,    52,     0,    23,    23,    32,    55,    30,    54,
    33,    51,     0,    23,    23,    32,    30,    54,    33,    51,
     0,    23,    29,    56,    30,     0,    23,    29,    55,    30,
     0,    23,    29,    22,    30,     0,    21,    29,    56,    30,
     0,    21,    29,    55,    30,     0,    21,    29,    22,    30,
     0,     8,    29,    55,     0,    55,     0,    55,    24,    55,
     0,    55,    25,    55,     0,    55,    26,    55,     0,    55,
    27,    55,     0,    32,    55,    33,     0,    23,     0,    23,
    38,    20,    39,     0,    57,     0,    56,    24,    56,     0,
    56,    25,    56,     0,    56,    26,    56,     0,    56,    27,
    56,     0,    32,    56,    33,     0,    23,     0,    23,    38,
    20,    39,     0,    20,     0,     7,     0,    23,    32,    58,
    33,     0,    23,    32,    33,     0,     8,     0,    34,    56,
    37,    56,    35,     0,    56,     0,    56,    37,    58,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    97,    98,   101,   102,   105,   106,   107,   108,   109,   112,
   113,   114,   114,   117,   118,   121,   122,   123,   124,   125,
   126,   127,   128,   129,   130,   133,   134,   137,   137,   140,
   141,   142,   145,   146,   149,   150,   151,   152,   153,   154,
   155,   156,   159,   160,   163,   164,   165,   166,   167,   168,
   169,   170,   173,   174,   175,   176,   177,   178,   179,   180,
   181,   182,   183,   186,   187,   190,   191
};

static const char * const yytname[] = {   "$","error","$illegal.","TIP","BGIN",
"END","ASSIGN","PROCENT","POINT","MAIN","RETURN","LOOP","POOL","IF","FI","FOR",
"ROF","IN","ELSE","PRINT","NR","PROPERTY","STRING","ID","'+'","'-'","'*'","'/'",
"'.'","'='","';'","'#'","'('","')'","'{'","'}'","'~'","','","'['","']'","progr",
"multiple_define","define","function_decl","@1","@2","stmt_sequence","stmt",
"param_list","main_body","@3","content","declaratii","declaratie","position",
"tup_expression","expression","tup","param_list_oncall",""
};
#endif

static const short yyr1[] = {     0,
    40,    40,    41,    41,    42,    42,    42,    42,    42,    44,
    43,    45,    43,    46,    46,    47,    47,    47,    47,    47,
    47,    47,    47,    47,    47,    48,    48,    50,    49,    51,
    51,    51,    52,    52,    53,    53,    53,    53,    53,    53,
    53,    53,    54,    54,    55,    55,    55,    55,    55,    55,
    55,    55,    56,    56,    56,    56,    56,    56,    56,    56,
    56,    56,    56,    57,    57,    58,    58
};

static const short yyr2[] = {     0,
     2,     1,     1,     2,     5,     5,     5,     1,     7,     0,
     8,     0,     9,     1,     2,     6,     8,     6,    10,     4,
     4,     3,     3,     3,     5,     1,     3,     0,     7,     1,
     3,     2,     1,     2,     8,     7,     4,     4,     4,     4,
     4,     4,     3,     1,     3,     3,     3,     3,     3,     1,
     4,     1,     3,     3,     3,     3,     3,     1,     4,     1,
     1,     4,     3,     1,     5,     1,     3
};

static const short yydefact[] = {    28,
     0,     0,    28,     3,     8,     2,     0,     0,     0,     1,
     4,     0,     0,     0,     0,     0,    61,    64,    60,     0,
    50,     0,     0,     0,     0,    52,    26,    10,     0,    50,
     0,     0,     0,     7,     0,     0,     0,     0,    58,     0,
     0,     0,     0,     0,     0,     5,     0,     0,     0,     0,
     6,     0,     0,    12,     0,     0,     0,    63,    66,     0,
     0,    49,    57,     0,     0,    45,    46,    47,    48,    53,
    54,    55,    56,    27,     0,     0,     0,     0,     0,     0,
    62,    51,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    14,     0,    51,    30,     0,     9,    29,    67,    59,
    65,     0,     0,     0,     0,     0,     0,     0,     0,    11,
    15,     0,     0,     0,    32,     0,    33,    24,    23,    22,
     0,     0,     0,     0,     0,     0,    13,     0,     0,     0,
    31,    34,     0,     0,     0,     0,    21,    20,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    25,    42,
    41,    40,     0,     0,    39,    38,    37,    18,    16,     0,
     0,    64,     0,    44,     0,     0,     0,     0,     0,     0,
    17,     0,    43,    36,     0,     0,    35,    19,     0,     0,
     0
};

static const short yydefgoto[] = {   179,
     3,     4,     5,    53,    76,    91,    92,    29,     6,     7,
    97,   116,   117,   163,    37,    38,    26,    60
};

static const short yypact[] = {    53,
   -19,   -10,-32768,    53,-32768,-32768,    14,    98,     3,-32768,
-32768,    23,     2,   -18,    77,    77,-32768,-32768,-32768,    16,
   -21,    99,    54,   195,   202,-32768,    28,-32768,    62,    55,
    77,   209,   216,-32768,    56,    83,    -6,   157,     1,    54,
   132,    77,    77,    77,    77,-32768,    54,    54,    54,    54,
-32768,    81,    74,-32768,    93,    87,   104,-32768,   136,   109,
    96,-32768,-32768,   106,    54,   118,   118,-32768,-32768,   122,
   122,-32768,-32768,-32768,   128,   112,   111,    17,    17,    54,
-32768,-32768,   114,   153,    30,   100,   138,   139,   142,   143,
   133,   128,   128,-32768,-32768,    -9,-32768,-32768,-32768,-32768,
-32768,   145,   223,   230,    54,    54,   162,    54,    99,-32768,
-32768,   151,   158,    95,-32768,   154,    33,-32768,-32768,-32768,
   167,   171,   182,   181,   237,   244,-32768,    37,   169,    60,
-32768,-32768,   128,   128,    54,   172,-32768,-32768,   173,   251,
   258,    82,   183,   265,   272,   203,    52,   140,-32768,-32768,
-32768,-32768,   102,   279,-32768,-32768,-32768,-32768,-32768,   128,
    54,   187,   184,   286,   102,   210,   185,    77,    17,   190,
-32768,   128,   286,-32768,    17,   214,-32768,-32768,   231,   238,
-32768
};

static const short yypgoto[] = {-32768,
   233,-32768,-32768,-32768,-32768,   -85,-32768,   192,   242,-32768,
   -78,   134,-32768,    94,   -13,    -7,-32768,   178
};


#define	YYLAST		313


static const short yytable[] = {    24,
    98,    32,    33,     8,    27,    25,   111,   112,    17,    18,
    35,   113,     9,   114,    28,    41,    36,    42,    43,    44,
    45,    19,    12,    20,    21,   115,    62,    59,    66,    67,
    68,    69,    35,    22,    15,    23,    17,    18,    64,    70,
    71,    72,    73,    17,    18,    34,    95,   146,   147,    19,
    96,   102,    21,   113,    16,   114,    19,    84,   139,    21,
    17,    22,    17,    23,    52,   159,    17,    18,    22,   160,
    23,   103,    59,    19,   166,    19,    39,   104,    39,    19,
     1,   143,    21,     2,    18,    40,   176,    40,    58,    18,
   174,    22,    55,    23,    54,   125,   177,   121,   122,    30,
   124,   126,    61,    27,    30,    17,    18,    75,    31,   162,
    23,   153,    77,    31,   140,    23,   144,   129,    19,    78,
   141,    21,   145,   130,    30,    83,    13,   148,   154,    14,
    22,   105,    23,    31,    82,    23,    79,    85,    86,   164,
    87,    81,    88,    44,    45,    93,    89,    49,    50,    94,
    90,   164,   100,   167,   173,    47,    48,    49,    50,    47,
    48,    49,    50,    47,    48,    49,    50,   110,    65,   106,
   107,   109,    80,   108,   118,   161,    47,    48,    49,    50,
    47,    48,    49,    50,   123,   127,   128,   101,   131,    63,
    47,    48,    49,    50,    47,    48,    49,    50,   135,   133,
   142,   149,   150,   134,    47,    48,    49,    50,    47,    48,
    49,    50,   155,   136,   158,   168,   169,   172,    42,    43,
    44,    45,   175,   171,    46,    47,    48,    49,    50,   178,
   180,    51,    42,    43,    44,    45,    11,   181,    56,    42,
    43,    44,    45,    74,    10,    57,    42,    43,    44,    45,
   132,     0,   119,    47,    48,    49,    50,    99,   170,   120,
    42,    43,    44,    45,     0,     0,   137,    47,    48,    49,
    50,     0,     0,   138,    42,    43,    44,    45,     0,     0,
   151,    47,    48,    49,    50,     0,     0,   152,    42,    43,
    44,    45,     0,     0,   156,    47,    48,    49,    50,     0,
     0,   157,    42,    43,    44,    45,     0,     0,   165,    42,
    43,    44,    45
};

static const short yycheck[] = {    13,
    79,    15,    16,    23,    23,    13,    92,    93,     7,     8,
    32,    21,    23,    23,    33,    23,    38,    24,    25,    26,
    27,    20,     9,    22,    23,    35,    33,    35,    42,    43,
    44,    45,    32,    32,    32,    34,     7,     8,    38,    47,
    48,    49,    50,     7,     8,    30,    30,   133,   134,    20,
    34,    22,    23,    21,    32,    23,    20,    65,    22,    23,
     7,    32,     7,    34,    37,    14,     7,     8,    32,    18,
    34,    85,    80,    20,   160,    20,    23,    85,    23,    20,
    28,    22,    23,    31,     8,    32,   172,    32,    33,     8,
   169,    32,    38,    34,    33,   109,   175,   105,   106,    23,
   108,   109,    20,    23,    23,     7,     8,    34,    32,     8,
    34,    30,    20,    32,   128,    34,   130,    23,    20,    33,
   128,    23,   130,    29,    23,    20,    29,   135,   142,    32,
    32,    32,    34,    32,    39,    34,    33,    10,    11,   153,
    13,    33,    15,    26,    27,    34,    19,    26,    27,    39,
    23,   165,    39,   161,   168,    24,    25,    26,    27,    24,
    25,    26,    27,    24,    25,    26,    27,    35,    37,    32,
    32,    29,    37,    32,    30,    36,    24,    25,    26,    27,
    24,    25,    26,    27,    23,    35,    29,    35,    35,    33,
    24,    25,    26,    27,    24,    25,    26,    27,    17,    33,
    32,    30,    30,    33,    24,    25,    26,    27,    24,    25,
    26,    27,    30,    33,    12,    29,    33,    33,    24,    25,
    26,    27,    33,    14,    30,    24,    25,    26,    27,    16,
     0,    30,    24,    25,    26,    27,     4,     0,    30,    24,
    25,    26,    27,    52,     3,    30,    24,    25,    26,    27,
   117,    -1,    30,    24,    25,    26,    27,    80,   165,    30,
    24,    25,    26,    27,    -1,    -1,    30,    24,    25,    26,
    27,    -1,    -1,    30,    24,    25,    26,    27,    -1,    -1,
    30,    24,    25,    26,    27,    -1,    -1,    30,    24,    25,
    26,    27,    -1,    -1,    30,    24,    25,    26,    27,    -1,
    -1,    30,    24,    25,    26,    27,    -1,    -1,    30,    24,
    25,    26,    27
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 6:
#line 106 "fe.y"
{if (!assign(yyvsp[-3].strval, yyvsp[-1].intval, consts, 0)) printf("Nu s-a putut asigna la identificatorul %s: exista deja o constanta cu acelasi nume\n", yyvsp[-3].strval);;
    break;}
case 10:
#line 113 "fe.y"
{enterEnv();;
    break;}
case 11:
#line 113 "fe.y"
{printf("In functia %s am avut:\n", yyvsp[-6].strval); printEnv(last_env); printf("Din care globale:\n"); printEnv(consts); exitEnv();;
    break;}
case 12:
#line 114 "fe.y"
{enterEnv();;
    break;}
case 13:
#line 114 "fe.y"
{exitEnv();;
    break;}
case 20:
#line 125 "fe.y"
{assign(yyvsp[-3].strval, yyvsp[-1].intval, last_env, 1);;
    break;}
case 25:
#line 130 "fe.y"
{printf("Am printat: %d\n", yyvsp[-2].intval);;
    break;}
case 28:
#line 137 "fe.y"
{enterComp("win");;
    break;}
case 29:
#line 137 "fe.y"
{struct window *win = (struct window *)(last_comp->value); win->size=yyvsp[-3].tupleval; createWindow(win); exitComp();;
    break;}
case 42:
#line 156 "fe.y"
{char* prop = (yyvsp[-3].strval)+1; char* value = yyvsp[-1].strval+1; value[strlen(value)-1]=0; applyProperty(prop, last_comp, value);;
    break;}
case 44:
#line 160 "fe.y"
{yyval.tupleval = yyvsp[0].tupleval;;
    break;}
case 49:
#line 167 "fe.y"
{yyval.tupleval = yyvsp[-1].tupleval;;
    break;}
case 52:
#line 170 "fe.y"
{struct tuple *ans;  ans=yyvsp[0].tupleval; yyval.tupleval = yyvsp[0].tupleval;;
    break;}
case 53:
#line 173 "fe.y"
{yyval.intval = yyvsp[-2].intval + yyvsp[0].intval;;
    break;}
case 54:
#line 174 "fe.y"
{yyval.intval = yyvsp[-2].intval - yyvsp[0].intval;;
    break;}
case 55:
#line 175 "fe.y"
{yyval.intval = yyvsp[-2].intval * yyvsp[0].intval;;
    break;}
case 56:
#line 176 "fe.y"
{yyval.intval = yyvsp[-2].intval / yyvsp[0].intval;;
    break;}
case 58:
#line 178 "fe.y"
{yyval.intval = getById(yyvsp[0].strval, last_env, consts);;
    break;}
case 60:
#line 180 "fe.y"
{yyval.intval = yyvsp[0].intval;;
    break;}
case 65:
#line 187 "fe.y"
{struct tuple *ans = malloc(sizeof(struct tuple)); ans->x=yyvsp[-3].intval; ans->y=yyvsp[-1].intval; yyval.tupleval = ans;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 194 "fe.y"

int yyerror(char * s){
printf("eroare: %s la linia:0\n",s);
}

int main(int argc, char** argv){
     yyin=fopen(argv[1],"r");
     struct environment* c = (void *)malloc(sizeof(struct environment));
     consts = c;
     enterEnv();
     yyparse();
     exitEnv();
} 
